swaywm/wlroots-rs

src/compositor.rs, src/manager/output.rs, src/manager/output_manager.rs, src/types/output.rs
Fixes #11 
This also fixes an issue where the output would "flicker" once plugged back in due to re-used state/callbacks.
Lots of data being flung around though, better check if I can unify how
I store it / reduce the amount of data passed around.
=> Clean up output data when an output is removed

examples/pointer.rs
The layout initialization was accidentally caught in the comment out period before we fix #34
=> Fixed pointer example so it runs again

src/types/area.rs, src/types/mod.rs, src/types/output.rs, wlroots-sys/src/lib.rs
Updated wlroots to the latest version (to get the latest wlr_box functions)
Added `Area`, a wrapper for `wlr_box`. Obviously can't call it `Box` because that's a type in Rust and otherwise you'd always need to qualify it with `wlroots::Box` and that's just obnoxious.
=> wlr_box Wrapper, updated wlroots

Cargo.toml, README.md, rootston/Cargo.toml, rootston/rootston.ini.example, rootston/src/config.rs, rootston/src/main.rs, src/lib.rs
Start of the rootston reference compositor in 100% safe Rust. :tada:
Large parts of the API still isn't done, but I thought it prudent to start the reference compositor now as it's something easier to build towards. The examples were good for a "just getting started" part of the library, but now that they are (mostly) 1-1 with the ones in the wlroots repo it's time to have a more comprehensive test.
This part of the work is just the ini file parsing, it can handle the exact same configuration files as the original rootston. 
Note that that "100% guarantee" is already violated with this PR, but since it has to do with ini parsing of xkb tokens, which isn't actually part of the surface API of wlroots-rs at all, it's not a huge issue at the moment. Maybe if I find that I need to that often …
=> Start of Rust rootston

src/compositor.rs, src/lib.rs, src/types/mod.rs, src/types/seat/grab.rs, src/types/seat/mod.rs, src/types/seat/seat.rs, src/types/seat/seat_client.rs, src/types/seat/touch_point.rs, src/types/surface.rs, src/utils.rs, wlroots-sys/src/lib.rs
* Allow (unsafe) access to display and event_loop pointers
* Wrapped grabs
* Wrapped Seat and Seat Clients
* Wrapped Touch Points
* Stubbed out surfaces
* Added `c_to_rust_string`
* Added `ToMS` trait, implemented for `std::time::Duration` to convert it to milliseconds
=> Wrapped wlr_seat

examples/pointer.rs, examples/rotation.rs, examples/simple.rs, src/manager/input_manager.rs, src/manager/keyboard_handler.rs, src/manager/output_handler.rs, src/manager/output_manager.rs, src/manager/pointer_handler.rs, src/render/gles2.rs, src/types/keyboard.rs, src/types/output.rs, src/types/pointer.rs
Stealing a bit from [wlc.rs](https://github.com/Drakulix/wlc.rs) here, I changed how `Keyboard`, `Pointer`, and `Output` function by making some "owned" types that are passed by reference in the callbacks (so just like before) and a `*Handle` struct for each type that can be constructed from those owned types.
E.g, given a `Pointer` you can make a `PointerHandle` which you can store within your compositor state. Internally, it uses an `Rc<()>`/`Weak<()>` (so essentially just a non-atomic counter) to ensure that when you use a handle it will actually exist. To use this safely, you pass it a callback to `run` that will execute code within a limited context that ensures that the handle is valid (e.g as long as we are in this callback, it's valid to use).
I haven't done this with …
=> Handle-ify wlroots owned objects

src/events/key_events.rs, src/events/pointer_events.rs, src/lib.rs, src/manager/input_manager.rs, src/manager/keyboard_handler.rs, src/manager/output_handler.rs, src/manager/pointer_handler.rs, src/render/gles2.rs, src/render/texture.rs, src/types/cursor.rs, src/types/input_device.rs, src/types/keyboard.rs, src/types/output.rs, src/types/pointer.rs, src/types/seat/seat.rs, src/types/seat/seat_client.rs
* Document key events
* Document pointer events
* Converted all `to_ptr` to `as_ptr`
* No longer expose the `from_ptr` methods on the pointer events
* Wrapped `wlr_button_state` with type `ButtonState` (to make it seem less gross even though it's a generated type from wlroots_sys)
* Can no longer get an `InputDevice` from the pointer events. Instead, it's bound to the lifetime of the event.
* Can now get a reference to the underlying `InputDevice` from the concrete device type (e.g `Keyboard` or `Pointer`)
=> Fixed InputDevice safety hole, allow conversions from concrete device types

src/types/area.rs, wlroots-sys/build.rs
Fixed issue in build system from the change of adding a config.h to the build output and using that to determine features.
Fixed Area::intersection to have new signature (a nicer one that's way less dumb)
=> Updated to wlroots c69042

src/compositor.rs, src/macros.rs, src/utils.rs
The way it works is that we add it to the macro so that all callbacks from the handler traits will have to go through a panic catcher that will stop it from unwinding back into wlroots/wayland.
Once we catch it, we then terminate the compositor and let the rest of the code run (which won't be much, since we called wl_display_terminate it will stop the loop getting events and just let the rest of the code, of which there is 0 in the macro, run to completion and pop back up the stack back into C land).
Before terminating the compositor, we store the error in the Compositor structure so that we can re-throw it later.
Once it's terminated, in our mainloop function we check the internal error conditional that's set when a panic is thrown (see above). If it's set, then we re-throw using …
=> Add panic catchers so we don't unwind into C

src/errors.rs, src/lib.rs, src/manager/input_manager.rs, src/manager/keyboard_handler.rs, src/manager/output_handler.rs, src/manager/output_manager.rs, src/manager/pointer_handler.rs, src/types/keyboard.rs, src/types/output.rs, src/types/pointer.rs
Plug safety hole from multi mut handles 
This plugs the hole that can be caused from running multiple handles within the `run` callback that all point to the same backing wlroots owned storage.
It was probably safe, tbh, because internally they all use *mut to get their data and it probably syncs that up just fine (e.g there's no incorrect way for Rust to re-order / elide the data fetching because it's behind an opaque barrier). However, UB is UB, so this limitation has been added.
The solution is to add an AtomicBool to the Rc in the concrete types and check that each time we acquire it. This means we can no longer expose the unsafe `upgrade` function, but that's not a problem since that wasn't supposed to be used anyways. The reason we can't expose it is that there's no way to set the …
=> Fix multiple mutable borrows from using handles

examples/pointer.rs, examples/rotation.rs, examples/simple.rs, src/events/key_events.rs, src/types/keyboard.rs, src/types/output.rs, src/types/pointer.rs
Added:
* `time_msec`
* `update_state`
- What is this? is this useful? This needs to be much better documented.
* `key_state`
* `input_keys` -> `pressed_keys`
* `ModifierMasks`
* `RepeatInfo`
* `set_keymap`
* `get_keymap`
* `keycodes`
* `led_list`
* `modifier_list`
* `keymap_size`
* `get_xkb_state`
* `repeat_info`
* `get_modifier_masks`
* Fixed documentation about panicking (forgot about it in last PR)
=> Finish wrapping Keyboard

examples/pointer.rs, src/macros.rs, src/types/cursor/cursor.rs, src/types/cursor/mod.rs, src/types/cursor/xcursor.rs, src/types/keyboard.rs, src/types/output/output.rs, src/types/output/output_layout.rs, src/types/pointer.rs
Fixes #33 and Fixes #35 (mostly, there are some things that are being split off into separate issues).
Split up `types/cursor.rs` into `types/cursor/xcursor.rs` and `types/cursor/cursor.rs`.
* impl `Eq` and `PartialEq` for all `*Handle` types.
* Add a type that returns a borrow of this structure
* Adds the rest of the functions for this.
* Fixed lifetime for `XCursor`
- Now that `XCursorTheme` has a destructor, the `XCursor` needs to live as long as the theme. The lifetime has been added, and now the correct usage is to store the `XCursorTheme` instead of an `XCursor` if you want to reuse it when constructing cursors.
- Note that this technically wasn't unsound before because we didn't free the structure, but I'll mark it as unsound regardless.
* Added rest of functions
* Removed unused …
=> Finished wrapping Cursor, XCursor, and XCursorTheme

examples/pointer.rs, examples/rotation.rs, examples/simple.rs, src/manager/output_handler.rs, src/manager/output_manager.rs, src/types/cursor/cursor.rs, src/types/cursor/xcursor.rs, src/types/output/mod.rs, src/types/output/output.rs, src/types/output/output_cursor.rs, src/types/output/output_layout.rs, src/types/output/output_mode.rs
Add rest of functions for `Output` (Fixes #38)
Does a lot of work for #41, but doesn't totally clear it just yet. It still needs work on setting the surface/buffer contents and to ensure it's safe to use.
Renamed the output callback functions.
Fixes `Cursor::map_to_output` to take an optional output.
=> Wrapped rest of Output, added OutputCursor

Cargo.toml, examples/minimal.rs, examples/pointer.rs, examples/rotation.rs, examples/simple.rs, examples/wl_shell_test.rs, src/compositor.rs, src/events/mod.rs, src/events/wl_shell_events.rs, src/lib.rs, src/manager/mod.rs, src/manager/wl_shell_handler.rs, src/manager/wl_shell_manager.rs, src/render/gles2.rs, src/types/mod.rs, src/types/seat/mod.rs, src/types/shell/mod.rs, src/types/shell/wl_shell.rs
Fixes #23.
Adds the ability to make a Wayland shell handler that handles incoming requests from clients.
Currently we don't have anything beyond a minimal wrapper for `Surface`s so there's no drawing done but the client and wlroots-rs can communicate over Wayland so it's a start.
* Added `WlShellManagerHandler` to builder.
* Made all of the handlers optional.
* Modified the setup process significantly.
- Passes the Wayland shell manager the render pointer if GLES2 is enabled
- Handles the cases where some number of the managers aren't enabled
- Correctly set `WAYLAND_DISPLAY` so that clients can talk to the compositor
* Added `WlShellManagerHandler`, a way to manage incoming shell connections
* Added `WlShellHandler`, a trait you implement on the state you want to have for each Wayland …
=> Wayland Shells

examples/pointer.rs, examples/simple.rs, src/compositor.rs, src/manager/input_manager.rs, src/manager/output_handler.rs, src/manager/output_manager.rs, src/render/renderer.rs, src/types/area.rs, src/types/keyboard.rs, src/types/output/output.rs, src/types/surface.rs
* Updated wlroots to 7da653bbb4569d41ce1a46c97e3b10c675f73741
* No longer has a callback for a destruction of any output (it was made redundant)
* `swap_buffers` now takes in optional values used for damage tracking, which are currently not utilized by wlroots-rs.
* `make_current` now returns information useful for damage tracking.
* Renderer does not do damage tracking, an API to enable this gracefully will be added in the future.
* `Area::transform` now takes a `width` and `height`.
=> Wlroots update

examples/wl_shell_test.rs, src/compositor.rs, src/lib.rs, src/macros.rs, src/manager/input_manager.rs, src/manager/output_manager.rs, src/manager/wl_shell_handler.rs, src/types/output/output.rs, src/types/seat/mod.rs, src/types/seat/seat.rs, src/types/seat/seat_client.rs, src/types/surface.rs
Implemented Seat, Fixes #37. Seats are spawned and managed by wlroots-rs and can be accessed by name.
Added null checks to the global compositor pointer.
Added `Output::schedule_frame`
Made the functions created by `wayland_listener!` `pub(crate)`
=> Implemented Seat

src/types/seat/mod.rs, src/types/seat/seat.rs
Now uses a `SeatId` to access the seats stored in the `Compositor` instead of the name. Re-added `Seat::set_name`.
=> Seats now accessed by id rather than by name

wlroots-sys/Cargo.toml
The warning was starting to get annoying. We don't care about wlroots' `.travis.yml`
=> Fixed warning about future exclusion

examples/minimal.rs, examples/pointer.rs, examples/rotation.rs, examples/simple.rs, examples/touch.rs, examples/wl_shell_test.rs, src/compositor.rs
This makes it much more ergnomic to only select some of the managers,
and also makes it more clear what's being constructed.
The minimal example is now much, much simpler :)
=> Managers are now totally in builder steps

.travis.yml, examples/rotation.rs, examples/touch.rs, src/events/tablet_tool_events.rs, src/events/touch_events.rs, src/manager/xdg_shell_v6_manager.rs, src/render/renderer.rs, src/render/texture.rs, src/types/cursor/cursor.rs, src/types/shell/xdg_shell_v6.rs, wlroots-sys/build.rs
Latest from the hackathon before I go. This has various changes
Can't create an invalid texture, API has increased (and thus more wrapping will be necessary)
No longer send width/height information explicitly
links to various xcb libraries now
=> Update to latest wlroots...again

Cargo.toml
Without this, the "static" feature of wlroots-sys is always enabled,
since it is the default. With this, "static" is still on by default
since wlroots-rs has default = ["static"]. However, now this can be
disabled by building wlroots-rs without default features.
Signed-off-by: Uli Schlachter <psychon@znc.in>
=> Disable default features for wlroots-sys

rootston/src/input.rs, src/macros.rs, src/types/input/keyboard.rs, src/types/input/pointer.rs, src/types/input/tablet_pad.rs, src/types/input/tablet_tool.rs, src/types/input/touch.rs
Can no longer construct InputDevice from an invalid input handle.
Also makes `run_handles!` easier to use.
=> Fixes #134

Cargo.toml, wlroots-sys/Cargo.toml, wlroots-sys/build.rs
Will by default attempt to find them and link to them. If they cannot befound, does not link to them.
Should do the right thing out of the box, but if not there's configurable feature flags.
Does this work with your setup @psychon?
=> Optional libcap, systemd, elogind dependencies

rootston/src/input.rs, src/compositor.rs, src/lib.rs, src/macros.rs, src/manager/input_manager.rs, src/manager/keyboard_handler.rs, src/manager/output_handler.rs, src/manager/output_manager.rs, src/manager/pointer_handler.rs, src/manager/tablet_pad_handler.rs, src/manager/tablet_tool_handler.rs, src/manager/touch_handler.rs, src/manager/wl_shell_handler.rs, src/manager/wl_shell_manager.rs, src/manager/xdg_shell_v6_handler.rs, src/manager/xdg_shell_v6_manager.rs, src/render/renderer.rs, src/types/cursor/cursor.rs, src/types/output/output_layout.rs, src/types/seat/seat.rs, src/xwayland/manager.rs
In Way Cooler we need access to the compositor state during Lua calls when we are not in the wayland event loop (because Way Cooler is single threaded).
To that end, I have added a function allowing the user to execute some code in the context of the compositor called `with_compositor`.
These series of patches also fixes a critical error made in `CursorHandle`, `SeatHandle`, and `OutputHandle`. You could upgrade these even when you were currently borrowing the concrete type in a callback. That has now been fixed.
Also fixed base case in `run_handles!`
Added `create_texture_from_pixels` onto the `Renderer` (exactly the same as `GenericRenderer`).
=> Allow global compositor access outside of the wayland event loop

src/compositor.rs, src/types/input/input_device.rs, src/types/seat/seat.rs, src/types/shell/xdg_shell_v6.rs, src/xwayland/server.rs
Summary:
* xwayland create got the `lazy` boolean flag, which means to start xwayland only after an X client tries to connect.
* xdg_popup_v6 lost the `position()` function (which you probably don't need because you normally have the toplevel first).
* the seat axis functions gained `axis_discrete` for the discrete number of axis steps (part of the Wayland protocol) and the axis source (also part of the Wayland protocol).
=> update to latest wlroots

examples/pointer.rs, examples/rotation.rs, examples/simple.rs, examples/tablet.rs, examples/touch.rs, examples/wl_shell_test.rs, examples/xdg_shell_v6_test.rs, src/compositor.rs
This allows Way Cooler to properly shutdown the glib loop and fail when a panic occurs.
This makes only the global terminate function public. This simplifies the API, but it is a breaking change.
=> Added custom terminate function

src/manager/xdg_shell_v6_handler.rs, src/manager/xdg_shell_v6_manager.rs
These events are needed for the xdg-shell-v6 implementation in way-cooler.
=> add map and unmap events to xdg-v6-surface

examples/pointer.rs, examples/xdg_shell_v6_test.rs, src/compositor.rs, src/types/cursor/cursor.rs, src/types/input/keyboard.rs, src/types/input/pointer.rs, src/types/input/tablet_pad.rs, src/types/input/tablet_tool.rs, src/types/input/touch.rs, src/types/output/output.rs, src/types/output/output_layout.rs, src/types/seat/seat.rs, src/types/shell/wl_shell.rs, src/types/shell/xdg_shell_v6.rs, src/types/surface/sub_surface.rs, src/types/surface/surface.rs, src/xwayland/surface.rs
Changed the `run` methods on `*Handle` types to only require an immutable reference to the handle instead of a mutable reference.
The mutable requirement doesn't add anything at all. It's not UB because we aren't modifying the Handle at all when we do that unsafely, it only makes it _slightly_ more clear there's mutation going on. But it's a red herring. The mutation is done on the backing structure which _is_ `&mut` so there's nothing bad there.
This is an issue because in Way Cooler we want to refer to the same handle across data structures (e.g the focus shell in both the global list of shells and in the abstraction over the seat to keep track of the focused one) and it's not possible without resorting shoe-horning it into one data structure or by keeping an ugly `Rc<RefCell<T>>` …
=> Lenient handle upgrades

src/events/seat_events.rs
A null surface means unset the client cursor.
=> allow null surface for client cursors

examples/xdg_shell_v6_test.rs, src/compositor.rs, src/manager/xdg_shell_handler.rs, src/manager/xdg_shell_manager.rs, src/manager/xdg_shell_v6_handler.rs, src/manager/xdg_shell_v6_manager.rs, src/types/shell/xdg_shell.rs, src/types/shell/xdg_shell_v6.rs, src/types/surface/sub_surface.rs, src/types/surface/surface.rs, src/xwayland/manager.rs, src/xwayland/server.rs, src/xwayland/surface.rs, wlroots-sys/src/wlroots.h
This PR fixes enough of the problems that #183 should be well and truely closed.
CC @acrisci to make sure the API is where it should be.
=> Surfaces are set up correctly, the destroy listener is removed correctly, subsurfaces has a manager, and also shells can specify surface handlers

examples/xdg_shell_v6_test.rs, src/macros.rs
Add another way to strip handles away. This one is much nicer than `with_handles` but has a few limitations that means you will still need `with_handles`.
With `dehandle!` you can nest handle unwrapping but without having to indent:
```rust
dehandle!(
@compositor = {compositor_handle}?;
let state: &mut State = compositor.into()
@shell = {state.shell_handle}?;
// do stuff with shell
).unwrap().unwrap();
```
However, as you can see from the above (short) example there are limations.
First of all the errors are no longer joined into one and must be dealt with separately. This means many `unwrap`s or many `?`. This is something that cannot be fixed with this macro.
However, if you omit the `?` it will automatically unwrap it (with a good `expect` message) which is _usually_ what you want. …
=> Dehandle macro

src/events/xdg_shell_events.rs, src/events/xdg_shell_v6_events.rs, src/events/xwayland_events.rs, src/utils.rs, wlroots-sys/src/wlroots.h
`wlr_edges` are an enum common to all the resize events to determine what edge is being resized.
=> implement wlr_edges

examples/rotation.rs, examples/touch.rs, src/render/renderer.rs, src/render/texture.rs, src/types/output/output_cursor.rs, src/types/surface/surface.rs
You can also destroy them now. This helps fix a bad memory leak in Way
Cooler (and any other WMs that create their own textures).
The memory model is a little weird, but it's required due to contraints
on when you can free the texture.
Specifically you can't free the texture when the renderer has begun
drawing, so it needs to be defined on the GenericRenderer.
Finally, you can only free ones you've created. In order to only have
one type, you can specify a type owned by the library user by creating
it and having the 'static lifetime associated with the struct. Only
instances with this lifetime can be freed (as otherwise it's handled
internally by wlroots, e.g. with surfaces from shell clients)
=> Fixed the safety hole with textures

Cargo.toml
Currently wlroots-rs isn't building because wlroots-sys requires the `unstable-features` feature to compile. This has been added to the default features for wlroots-sys, but wlroots-rs had the defaults disabled in PR #136. This change adds `unstable-features` to the defaults for wlroots-rs.
=> Add unstable-features to wlroots-rs

wlroots-sys/build.rs
When writing an hello-world compositor, I got "undefined reference" linking errors for symbols like "xcb_errors_get_name_for_major_code" when compiling. This PR fixes those errors for me.
=> Fix for linking errors

src/macros.rs, src/types/output/output.rs, src/types/output/output_damage.rs, src/types/surface/surface.rs
This is related to but does not 100% solve Issue #205.
The style difference (`::libc` versus `use libc::{ ... }`) is just because I used whatever I saw in the particular source file I was editing. `macros.rs` doesn't seem to `use`-import anything.
=> Use libc::{clock_t, c_char} to allow compilation on ARM

Cargo.toml, src/lib.rs, src/utils.rs
- Add the [vsprintf](https://docs.rs/vsprintf/1.0.1/vsprintf/) module
- Formatting the message in utils -> log_callback
**Before: **
**After: **
=> Use vsprintf to format the message to LogCallback

README.md, examples/pointer.rs
- Add the cargo command to run an example from the examples directory
- Cleaning the `pointer.rs` example
The following enhancements will also be added in future pull requests:
- Cleaning the `rotation.rs` example
- Cleaning the `tablet.rs` example
- Cleaning the `touch.rs` example
- Cleaning the `xdg_shell_v6_test.rs` example
=> Cleaning the pointer example

wlroots-sys/build.rs
It's optional in wlroots as well.
Noticed while building on Debian testing.
=> Make xcb-errors optional

src/lib.rs, src/macros.rs
Fixed a longstanding bug where you had to have `libc` in your compositor to use the logging in the library.
=> Fixed libc imports from macros

src/manager/xdg_shell_handler.rs, src/manager/xdg_shell_manager.rs
Nearly identical to the v6 implementation.
Needed to fix some shell bugs in way-cooler (test pr incoming).
=> xdg-shell: implement map and unmap events

src/xwayland/manager.rs, src/xwayland/surface.rs
On the new_surface event, the xwayland shell surface does not have a
cooresponding wlr_surface so trying to access it will segfault.
XWayland shell surfaces gain a new surface on each map event, so accept
the SurfaceHandler on that event instead of when the shell surface is
created.
Update some places in the code that assume the XWayland shell surface
will always have a wlr surface.
=> XWayland: fix segfault on new surface

Cargo.toml, src/compositor.rs, src/lib.rs, src/macros.rs, src/manager/drag_icon_handler.rs, src/manager/output_handler.rs, src/manager/xdg_shell_handler.rs, src/manager/xdg_shell_v6_handler.rs, src/types/output/output.rs, src/types/shell/xdg_shell.rs, src/types/shell/xdg_shell_v6.rs, wlroots-sys/Cargo.toml, wlroots-sys/build.rs, wlroots-sys/src/lib.rs
* Fixes shells not being destroyed properly during destruction of the compositor
+ Required updating wayland-rs
* Only wlroots-sys has wayland-rs now, this will simplify dependency management
* xdg shell user data properly cleaned up
* Removed all outdated dev dependencies
* Generally updated dependencies
=> Fix shell destruction, clean up xdg shell data, update wayland-rs

.build.yml, Cargo.toml, makefile, wlroots-dehandle/Cargo.toml, wlroots-sys/Cargo.toml
This is the default for libraries on linux, even though right now no one should really be doing this because wlroots doesn't guarantee any ABI compatibility for non-stable interfaces.
This will also fix the documentation generation at docs.rs
=> Dynamic link by default

.build.yml, Cargo.toml, wlroots-sys/Cargo.toml, wlroots-sys/build.rs
Adds the other wlroots feature flags that we didn't have from before (does not impact static builds).
Fixed dynamic builds, which should help docs.rs to build the docs properly.
=> Fix dynamic linking, add rest of wlroots feature flags

examples/pointer.rs, examples/rotation.rs, examples/tablet.rs, examples/touch.rs, examples/xdg_shell_v6_test.rs, src/compositor.rs, src/macros.rs, src/manager/input_manager.rs, src/manager/output_manager.rs, src/manager/xdg_shell_manager.rs, src/manager/xdg_shell_v6_manager.rs, src/types/input/input_device.rs, src/types/input/mod.rs, src/types/output/mod.rs, src/types/output/output.rs, src/types/shell/xdg_shell.rs, src/types/shell/xdg_shell_v6.rs, src/xwayland/manager.rs, src/xwayland/mod.rs, src/xwayland/server.rs
All the managers are now static functions that are built using builders that refer to static functions.
It never made sense to pay for the overhead of a trait object since:
1) There's only one manager per resource, so the vtable always is the same.
2) There's no way to swap them out, so the ability to refer to a different vtable is pointless.
3) In practice there was no manager specific state that the compositors writers had to keep that didn't end up having to be in the global compositor state (to share with the other resource managers).
This re-organizes a lot of things, including changing how the managers work so this is a **breaking change**.
Fixes #239
=> Static managers

src/compositor.rs
This fixes a glaring safety hole where you can reset the globalpointers, either while the compositor is running, after it was constructed, or even from another thread.
This also removes the possibility of a data race for the global function pointers in each resource manager. Before it was possible, now it is not.
=> Only one compositor::Builder per process

Cargo.toml, examples/minimal.rs, examples/pointer.rs, examples/rotation.rs, examples/tablet.rs, examples/touch.rs, examples/xdg_shell_v6_test.rs, src/lib.rs, src/utils/log.rs
Added a small Logger around `_wlr_log`. At the moment you'd have to use an external logger like env_logger, and maintain both verbosity levels, so that wlroots logs at the correct verbosity.
This allows it for the user to do what's currently possible with the `wlr_log!` macro, while allowing the user to use the standarized interface provided by the `log` crate.
Please check the mappings from the more detailed `FilterLevel`s `log` provides to the `enum wlr_log_importance`s.
=> Added log wrapper for wlr_log

Cargo.toml, examples/xdg_shell_v6_test.rs, wlroots-dehandle/Cargo.toml, wlroots-dehandle/src/lib.rs
The use syntax is a little gross, so I've decided to make it a bit clearer what the heck is going on by using a nested attribute to denote handle upgrades. Note that v1.0 is still valid, this is just easier to use (and also I threw `Span` in all the right places, so the errors will be much, much better now).
It also allows you to use `?` error handling, so it's strictly better than `with_handles` (though that will stick around).
The syntax before:
```rust
impl InputManagerHandler for InputManager {
#[wlroots_dehandle(compositor, keyboard, seat)]
fn keyboard_added(&mut self,
compositor_handle: CompositorHandle,
keyboard: KeyboardHandle)
-> Option<Box<Keyboard Handler>> {
{
use compositor_handle as compositor;
use keyboard as keyboard;
let server: &mut ::Server = compositor.into(); …
```
=> wlroots_dehandle 2.0

src/types/output/cursor.rs, src/utils/handle.rs
Fixes the error for when there are double borrows on `upgrade` which will make error handling much more sane.
Added `is_{alive,borrowed}` checks to the handles so you can peek at the info.
Fixed `output::Cursor` by using the above checks
=> Fixed handle errors and in output layout

wlroots-sys/build.rs
Hehe, in my haste with gamma protocol, I linked to the wrong one! It was linking to guicam's and not wlroots. This fixes that.
=> linking to wrong protocol, doh!

src/compositor.rs, src/extensions/idle.rs, src/extensions/mod.rs, wlroots-sys/build.rs, wlroots-sys/src/lib.rs, wlroots-sys/src/wlroots.h
Closes #100 
WIP as I can't get it to see the seat pointer. I was trying to do what server decoration does but :man_shrugging: 
Everything else is supposedly working according to cargo... :crossed_fingers: 
IF working, we can support swayidle now.
=> [WIP] Idle Support 

src/events/mod.rs, src/events/switch_events.rs, src/manager/input_manager.rs, src/manager/mod.rs, src/manager/switch_handler.rs, src/types/area.rs, src/types/input/input_device.rs, src/types/input/mod.rs, src/types/input/switch.rs, src/types/seat/seat.rs, src/types/shell/xdg_shell.rs
Updated to wlroots 0.3.
Fixes #251, ~though it's not ready to be tagged yet since `WLR_INPUT_DEVICE_SWITCH` isn't implemented properly.~ It has been basically implemented, though it requires testing. This version can now be tagged once it is merged.
=> wlroots 0.3

src/types/surface/subsurface.rs, src/types/surface/subsurface_manager.rs, src/types/surface/surface.rs
This was being overridden for each subsurface and would cause a segfault when the surface was inevitably cleaned up.
This only happens for complex clients, so I didn't find it out until alacritty was being tested for the book.
=> Removed bogus destroyed subsurface listener

examples/xdg_shell_v6_test.rs, src/compositor.rs
This is done to increase flexibility for three reasons:
1) If you want to spawn programs at startup you would need to set this
already, and setting it twice seems silly. So lets make it easier and
let that happen.
2) You may want to deny clients from connecting, though this is less a
security measure and more of a "lets lock this down or maybe forward it
to another compositor" use case. It's a small edge caset tbf.
3) It's trivial to do, so you don't lose much by having to do it
yourself.
Later on I might also make starting the backend a manual thing you must
do, but I need to ensure it's safe (the problem is I keep the Compositor
in a global `UnsafeCell` once I start the event loop, and I don't want
it to be possible to call the backedn start more than once so I'll need
to make it an …
=> Compositor writer manually sets WAYLAND_DISPLAY

src/compositor.rs, src/extensions/gamma_control.rs, wlroots-sys/src/wlroots.h
Fixed the Gamma Control extension to link to the wlroots protocol instead of the orbital protocol
Fixes #268
=> link to wlr_gamma instead of orbital gamma

src/compositor.rs
There's no need to make it use getters and setters, which are strictly
worse than direct access (due to partial borrows)
=> Make backend field on Compositor public

src/backend/headless.rs, src/compositor.rs, src/manager/output_handler.rs, src/manager/output_manager.rs, src/manager/xdg_shell_handler.rs, src/manager/xdg_shell_manager.rs, src/manager/xdg_shell_v6_handler.rs, src/manager/xdg_shell_v6_manager.rs, src/types/input/input_device.rs, src/types/input/keyboard.rs, src/types/input/pointer.rs, src/types/input/switch.rs, src/types/input/tablet_pad.rs, src/types/input/tablet_tool.rs, src/types/input/touch.rs, src/types/output/output.rs, src/types/seat/seat.rs, src/types/shell/xdg_shell.rs, src/types/shell/xdg_shell_v6.rs, src/types/surface/subsurface.rs, src/types/surface/surface.rs, src/utils/handle.rs, src/xwayland/manager.rs, src/xwayland/surface.rs
There was a use-after-free if `yad --entry` was ran in a compositor and then killed with `SIGTERM` (e.g. with ^C). This was because it was using the internal resource again when it upgraded the data. 
The first commit of this patch series is a naive fix. The rest of the commits are doing it better by changing how `Handle` stores its data. It now stores a `Option<D>`. This was done because we needed a default for `D` but `Default` isn't implemented for raw pointers (which most `D`s were).
However, since `D` was always a pointer it could have been null this would have added overhead. To keep the cost down, and because it was a big change already, I also switched all the internal pointers over to NonNulls. This added some noise in the code, but makes it much more difficult to have these sort …
=> Fix xdg surface use-after-free by switching to NonNull
