Cargo.toml
examples/pointer.rs
examples/simple.rs
src/events/key_events.rs
src/events/pointer_events.rs
src/lib.rs
src/macros.rs
src/manager/input_manager.rs
src/manager/keyboard.rs
src/manager/mod.rs
src/manager/pointer.rs
src/types/cursor.rs
src/types/input_device.rs
src/types/keyboard.rs
src/types/mod.rs
wlroots-sys/src/lib.rs

Now `KeyEvent` contains `Keyboard` handler, which may be used by user to get modifiers and set leds.
TODO: Add safe `set_keymap` function.

Add safe keyboard wrapper

---

src/manager/mod.rs
src/manager/output_manager.rs
src/manager/user_output.rs

Renamed Output to UserOutput

---

.travis.yml
examples/pointer.rs
src/types/cursor.rs
src/types/output.rs

@Timidger, hi.
I've updated wlroots-sys. Because of the new cursor management, I've deleted some cursor functions. As I understand, cursor will be fixed by #33.

Updated wlroots-sys to `aead501`

---

src/manager/input_manager.rs
src/manager/output_handler.rs
src/manager/pointer_handler.rs
src/types/cursor.rs
src/types/input_device.rs
src/types/keyboard.rs
src/types/output.rs
src/types/pointer.rs
src/types/seat/grab.rs
src/types/seat/seat.rs
src/types/seat/seat_client.rs
src/types/seat/touch_point.rs
src/types/surface.rs

It just adds noise and doesn't seem useful right now. If it's useful for compositor writers, it will be re-exposed later.

Don't expose raw pointer functions

---

wlroots-sys/Cargo.toml

Generated bindings are for wlroots

---

src/compositor.rs
src/lib.rs
src/types/data_device/data_source.rs
src/types/data_device/manager.rs
src/types/data_device/mod.rs
src/types/mod.rs

This does *not* totally finish up #31, but makes the types for it and allows it to be enabled via the `CompositorBuilder`.

Stubbed out Data device manager

---

src/render/renderer.rs

Small change made to the render construction, which doesn't affect the
API for wlroots-rs users

Updated wlroots (again)

---

rootston/src/input.rs
src/lib.rs
src/render/renderer.rs
src/types/cursor/cursor.rs
src/types/cursor/xcursor.rs
src/types/output/output.rs
src/types/output/output_cursor.rs
src/types/output/output_damage.rs
src/types/seat/seat.rs
src/types/shell/xdg_shell_v6.rs
src/utils.rs

Replaced Option arguments with Into<Option>

---

src/compositor.rs

Compositor::run() runs wayland's event loop via wl_display_run(). This
commit adds Compositor::run_with() which does exactly the same things as
run(), but instead of calling wl_display_run(), this calls a callback.
Thus, after this commit it is possible to use a different event loop
than libwayland's builtin one.
Signed-off-by: Uli Schlachter <psychon@znc.in>

Compositor: Allow replacing wl_display_run()

---

src/types/cursor/cursor.rs
src/types/input/keyboard.rs
src/types/input/pointer.rs
src/types/input/tablet_pad.rs
src/types/input/tablet_tool.rs
src/types/input/touch.rs
src/types/output/output.rs
src/types/output/output_layout.rs
src/types/seat/seat.rs
src/types/shell/wl_shell.rs
src/types/shell/xdg_shell_v6.rs
src/types/surface/sub_surface.rs
src/types/surface/surface.rs

There's no need for this to be atomic. This will improve performance.

Removed AtomicBool, switched to Cell<bool>

---

examples/pointer.rs
src/render/renderer.rs
src/types/cursor/cursor.rs
src/types/cursor/mod.rs
src/types/cursor/xcursor.rs
src/types/cursor/xcursor_manager.rs
wlroots-sys/src/wlroots.h

[WIP] xcursor manager

---

examples/xdg_shell_v6_test.rs

Some general fixups to the xdg-shell example to learn how things work.

Xdg shell example fixes

---

src/events/mod.rs
src/events/xwayland_events.rs
src/lib.rs
src/xwayland/hints.rs
src/xwayland/manager.rs
src/xwayland/mod.rs
src/xwayland/server.rs
src/xwayland/surface.rs

You can now use XWayland properly in wlroots-rs.
This should unblock a lot of things with Way Cooler now.
Fixes #138

Wrapped xwayland surfaces

---

src/types/shell/xdg_shell_v6.rs

Implement `wlr_xdg_surface_v6_for_each_surface`.

xdg-surface: for each surface

---

src/types/input/input_device.rs
src/types/input/keyboard.rs
src/types/input/pointer.rs
src/types/input/tablet_pad.rs
src/types/input/tablet_tool.rs
src/types/input/touch.rs

Finished wrapping Input device

---

examples/xdg_shell_v6_test.rs
src/utils.rs

add current_time util function

---

src/compositor.rs
src/manager/input_manager.rs
src/manager/keyboard_handler.rs
src/manager/output_handler.rs
src/manager/output_manager.rs
src/manager/pointer_handler.rs
src/manager/tablet_pad_handler.rs
src/manager/tablet_tool_handler.rs
src/manager/touch_handler.rs
src/types/output/output.rs

IO destruction listener fix

---

src/lib.rs
src/manager/drag_icon_handler.rs
src/manager/mod.rs
src/types/seat/drag_icon.rs
src/types/seat/mod.rs
src/types/seat/seat.rs

wlr drag icon

---

src/manager/xdg_shell_handler.rs
src/manager/xdg_shell_manager.rs
src/manager/xdg_shell_v6_handler.rs
src/manager/xdg_shell_v6_manager.rs
src/xwayland/manager.rs
src/xwayland/surface.rs

Allow optional setting of shell handlers

---

src/backend/drm.rs
src/backend/multi.rs
src/backend/session.rs
src/types/output/output.rs
src/types/seat/drag_icon.rs
wlroots-sys/build.rs

Might have to fix the session later, and there are some other API breakages.
This is a big update change, so it probably fixes a lot of outstanding bugs that wlroots had (one of which I was running into in Way Cooler).

updated wlroots

---

examples/rotation.rs

- Grouping structs with their implementation
- Add `_handle` suffix to handle objects
- Replace `_` unused arguments to `_<name>` of argument for verbosity
- Add helper method to convert `str` to `wl_output_transform`
- Add helper in `CompositorState` to register a frame (delta time calculation)
- Add `Vector2` struct to simplify `offset` and `velocity`
- Remove the `update_velocities` helper method to use the Vector2's `increment` instead
- More verbose variable names (ex: `rotation_transform` instead of
`rotation`)
- Remove the helper step by iterator, `step_by` on `iterator` is stable
since 1.28 (https://github.com/rust-lang/rust/blob/master/RELEASES.md#user-content-stabilized-apis-2)

Cleaning the rotation example

---

src/render/renderer.rs

Needed for [this toy](https://github.com/Timidger/tetris-wlroots) to compile

Added render_scissor function to Renderer

---

src/xwayland/surface.rs

* geometry() - get position and size of the surface
* configure() - set position and size of the surface
* set_activated() - tell the window whether it is focused

Add some Xwayland surface implementations

---

examples/xdg_shell_v6_test.rs
src/compositor.rs

* Made wl_shm optional (**breaking**), Fixes #235 
* Got rid of the `Option` around the internal compositor type (internal change)
* Formatting

Optional wl shm

---

src/backend/backend.rs
src/backend/session.rs
src/compositor.rs

Now allows us to switch TTYs and other things using this framework.

Expose session type properly

---

src/lib.rs
src/types/input/keyboard.rs
src/types/seat/seat.rs

This sounds like what you had in mind.
Closes #226

Add KeyboardModifiers wrapper

---

src/compositor.rs
src/extensions/gamma_control.rs
src/extensions/mod.rs
wlroots-sys/build.rs

Fixes #98 
Here's my attempt. Lemme know what you think. My Rust is still a little noobish but I, at least, understand what's going on with the code :)

Gamma Control Protocol

---

src/types/output/cursor.rs

Implements the rest of Output Cursor

---

src/compositor.rs
src/extensions/mod.rs
src/extensions/screenshooter.rs

closes #97 
Just like gamma control, I did the same process.

added screenshooter extension

---

examples/pointer.rs
examples/xdg_shell_v6_test.rs
src/types/cursor/cursor.rs
src/types/output/cursor.rs

Rename move_to to move_relative

---

src/extensions/gamma_control.rs
src/extensions/screenshooter.rs
src/extensions/server_decoration.rs

Documented the extensions module. I summarized the protocol and added a little as documentation. Each header specifies which protocol it supports.

Document the extensions

---

src/compositor.rs
src/extensions/mod.rs
src/extensions/screencopy.rs
wlroots-sys/build.rs
wlroots-sys/src/wlroots.h

Closes #262 
* Had to dig a little deeper and import the header file
* In Build.rs, I tried to make it look a little cleaner. I'll take a look at the macro you described when I can.
I'm planning to continue doing this. Protocols are fun :)

Screencopy Protocol Support

---

src/manager/drag_icon_handler.rs
src/types/seat/drag_icon.rs
src/types/seat/seat.rs

Wlroots 0.4 Compatibility

---

.build.yml

Added -D warnings to CI build flags

---

src/compositor.rs
src/extensions/idle_inhibit.rs
src/extensions/mod.rs
wlroots-sys/src/wlroots.h

Wrapped the idle inhibit protocol

Idle Inhibit Protocol

---

src/compositor.rs
src/extensions/input_inhibit.rs
src/extensions/mod.rs
wlroots-sys/src/wlroots.h

All inhibitor protocols should be wrapped now... I think.

Input Inhibit support
